version: '3.3'

volumes:
  static_value:
  media_value:
  result_build:
  postgres_data:
  redoc:


services:

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: insept17/foodgram:latest
    restart: always
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
      - redoc:/app/api/docs/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: insept17/foodgram_frontend:latest
    volumes:
      - result_build:/app/result_build/build/

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
      - result_build:/usr/share/nginx/html/
      - redoc:/usr/share/nginx/html/api/docs/ # - ../docs:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    env_file:
      - ./.env

      # Удалить куки браузера 
      # создать теги
      # сделать редок
      # Проверить статику (загрузить на сервак)